import '@/styles/globals.css'

import { type Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

import { Theme } from '@radix-ui/themes'
import { Toaster } from 'sonner'

import Header from '@/components/header'
import { cn } from '@/lib/utils'
import { TRPCReactProvider } from '@/trpc/react'

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={cn('min-h-screen', inter.variable)}>
        <ThemeProvider defaultTheme="light" enableSystem={false} attribute="class">
          <Theme>
            <TRPCReactProvider>
              <div className="flex min-h-screen flex-col">
                <Header />

                {/* eslint-disable-next-line @stylistic/max-len */}
                <main className="bg-gray-app h-full px-2 py-8 radix-xs:px-4 sm:px-6 md:px-8 lg:px-10 xl:px-12 2xl:px-16">
                  <div className="h-full 2xl:mx-auto 2xl:max-w-screen-2xl">
                    {children}
                  </div>
                </main>
              </div>

              <Toaster richColors />
            </TRPCReactProvider>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  )
}
